---
title: "USDA Validation"
format:
  dashboard:
    orientation: columns
    nav-buttons: []
execute:
  echo: false
  warning: false
theme: custom.scss
---

```{r setup, include=FALSE}
library(tidyverse)
library(arrow)
library(scales)
library(ggpubr)

# Load in data
df_ <- read_parquet("data/data_dump.parquet")

n_samples <- n_distinct(df_$sample)
n_reactions <- n_distinct(df_$reaction_id)
n_results <- n_distinct(df_$result_id)

theme_set(theme_minimal(base_size = 13))
```

# Overview

## Column {width="80%"}

### Row {height="15%"}
```{r}
#| content: valuebox
#| title: "Samples"
list(
  icon = "eyedropper",
  color = "primary",
  value = label_comma()(n_samples)
)
```

```{r}
#| content: valuebox
#| title: "Reactions"
list(
  icon = "grid-3x3",
  color = "info",
  value = label_comma()(n_reactions)
)
```

```{r}
#| content: valuebox
#| title: "Results"
list(
  icon = "clipboard-data",
  color = "success",
  value = label_comma()(n_results)
)
```

### Row {height="85%"}

#### Column {width="33.33%"}

```{r}
#| title: "Running Totals"
#| fig-height: 10
#| fig-width: 8
df_dates <- df_ %>%
  arrange(date) %>%
  summarise(
    n_samples = n_distinct(sample),
    n_reactions = n_distinct(reaction_id),
    n_results = n_distinct(result_id),
    .by = date
  ) %>%
  mutate(
    `Cumulative Samples` = cumsum(n_samples),
    `Cumulative Reactions` = cumsum(n_reactions),
    `Cumulative Results` = cumsum(n_results)
  )

plot_labs <- df_dates %>%
  select(date, `Cumulative Samples`, `Cumulative Reactions`, `Cumulative Results`) %>%
  pivot_longer(-1, names_to = "type", values_to = "count") %>%
  summarise(
    y = max(count),
    x = min(date),
    xend = max(date),
    .by = type
  )

df_dates %>%
  select(date, `Cumulative Samples`, `Cumulative Reactions`, `Cumulative Results`) %>%
  pivot_longer(-1, names_to = "type", values_to = "count") %>%
  ggplot(aes(x = date, y = count)) +
  geom_line() +
  geom_segment(aes(x = x, xend = xend, y = y), data = plot_labs, linetype = "dashed", color = "red") +
  geom_label(aes(x = x, y = y, label = label_comma()(y)), data = plot_labs, hjust = 0, ) +
  facet_wrap(vars(type), ncol=1, scales = "free_y") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") +
  scale_y_continuous(labels = label_comma(), n.breaks = 10) +
  labs(x = "", y = "Count") +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
  )
```


#### Column {width="33.33%"}

```{r}
#| title: "Samples by Sample Type"
#| fig-height: 10
#| fig-width: 8
df_sample_types <- df_ %>%
  mutate(
    sample_type = case_when(
      str_detect(sample_type, "oral") ~ "oral swab",
      str_detect(sample_type, "nasal") ~ "nasal swab",
      .default = as.character(sample_type)
    )
  ) %>%
  summarise(
    n_samples = n_distinct(sample),
    n_reactions = n_distinct(reaction_id),
    n_results = n_distinct(result_id),
    .by = sample_type
  )

df_sample_types %>%
  filter(sample_type != "PLN") %>%
  mutate(sample_type = fct_reorder(sample_type, n_samples, .desc = TRUE)) %>%
  ggplot(aes(x = sample_type, y = n_samples)) +
  geom_col(fill = "steelblue") +
  geom_label(aes(y=n_samples - 2, label = label_comma()(n_samples)), vjust = 1) +
  labs(x = "", y = "Samples")
```

## Column {width="33.33%"}

```{r}
#| title: "Pairwise Metric Correlation (log scale)"
#| fig-height: 14
#| fig-width: 8

# Explanation for log scaling --------------------------------------------
df_cor <- df_ %>%
  filter(str_detect(group, "Control") | mortem == "post-mortem" | mpi == 0) %>%
  mutate(
    across(c(mpr, ms, auc), log),
    positive = group == "Positive Control" | mortem == "post-mortem",
    positive = ifelse(positive, "Positive", "Negative")
  )

metric_combos <- c("mpr", "ms", "auc") %>%
  combn(2) %>%
  t() %>%
  as.data.frame() %>%
  rename(x = 1, y = 2)

make_cor_plot <- function(df, x, y, color_group, facet_group, alpha = 0.1) {
  df %>%
    ggplot(aes(.data[[x]], .data[[y]])) +
    geom_point(
      aes(
        color = .data[[color_group]],
        # shape = .data[[shape_group]]
      ), alpha = alpha, size=2) +
    scale_color_manual(values = c("navy", "red")) +
    scale_shape_manual(values = c(1, 2)) +
    labs(
      x = toupper(x),
      y = toupper(y),
      color = str_to_title(color_group),
      # shape = str_to_title(shape_group)
    ) +
    facet_wrap(vars(.data[[facet_group]]), ncol=2) +
    guides(
        color = guide_legend(override.aes = list(alpha = 1, size = 5, shape = "square"))
    ) +
    # main_theme +
    theme(
      legend.title = element_blank(),
      legend.text = element_text(size = 16),
      legend.key = element_rect(fill = "white", color = "white"),
      strip.text = element_text(size = 16, face = "bold"),
    )
}

cor_plots <- pmap(
  metric_combos,
  make_cor_plot,
  df = df_cor,
  color_group = "positive",
  facet_group = "assay",
  alpha = 0.1
)

ggarrange(
  plotlist = cor_plots, align = "hv", legend="bottom", ncol = 1,
  common.legend = TRUE, font.label = list(size = 30)
)
```
